exclude: ^(docs|tests/test_files|tasks.py)

ci:
  autoupdate_schedule: monthly
  skip: [mypy]
  autofix_commit_msg: pre-commit auto-fixes
  autoupdate_commit_msg: pre-commit autoupdate

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^tests
      - id: trailing-whitespace
        exclude: ^tests

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        stages: [pre-commit, commit-msg]
        exclude_types: [html]
        additional_dependencies: [tomli] # needed to read pyproject.toml below py3.11

  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.17.0
    hooks:
      - id: cython-lint
        args: [--no-pycodestyle]
      - id: double-quote-cython-strings

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.20.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        # MD013: line too long
        # MD024: Multiple headings with the same content
        # MD033: no inline HTML
        # MD041: first line in a file should be a top-level heading
        # MD025: single title
        args: [--disable, MD013, MD024, MD025, MD033, MD041, "--"]
